### ISSUE TITLE
Error using \include in source block

### ISSUE THREAD

**Issue by MasterOdin** [asciidoc/asciidoc-py3#119]
Attempting to convert the following fragment:

```
[cols="1,3,3"]
|===
|Language Feature |Markdown |AsciiDoc

|Includes
|_n/a_
a|
[source,text]
----
\include::intro.adoc[]
----
|===

```

causes the following error:
```
asciidoc: FAILED: <stdin>: line 2: unexpected error:
asciidoc: ------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/e/Github/asciidoc-py3/asciidoc.py", line 6121, in asciidoc
    has_header = document.parse_header(doctype, backend)
  File "/mnt/e/Github/asciidoc-py3/asciidoc.py", line 1562, in parse_header
    has_header = (Title.isnext() and Title.level == 0 and AttributeList.style() != 'float')
  File "/mnt/e/Github/asciidoc-py3/asciidoc.py", line 2048, in isnext
    lines = reader.read_ahead(2)
  File "/mnt/e/Github/asciidoc-py3/asciidoc.py", line 4525, in read_ahead
    while i < count and not self.eof():
  File "/mnt/e/Github/asciidoc-py3/asciidoc.py", line 4500, in eof
    return self.read_next() is None
  File "/mnt/e/Github/asciidoc-py3/asciidoc.py", line 4504, in read_next
    result = self.read()
  File "/mnt/e/Github/asciidoc-py3/asciidoc.py", line 4411, in read
    result = self.read_super()
  File "/mnt/e/Github/asciidoc-py3/asciidoc.py", line 4405, in read_super
    result = Reader1.read(self, self.skip)
  File "/mnt/e/Github/asciidoc-py3/asciidoc.py", line 4354, in read
    self.open(fname)
  File "/mnt/e/Github/asciidoc-py3/asciidoc.py", line 4244, in open
    self.f = open(fname, 'r', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'intro.adoc'
asciidoc: WARNING: test.asciidoc: line 12: filter non-zero exit code: "/usr/bin/python3" "/mnt/e/Github/asciidoc-py3/asciidoc.py" -b html5  --attribute "source-highlighter=pygments" -a "indir=/mnt/e/Github/asciidoc-benchmarks" -a "blockname=table" -s -: returned 1
asciidoc: WARNING: test.asciidoc: line 12: no output from filter: "/usr/bin/python3" "/mnt/e/Github/asciidoc-py3/asciidoc.py" -b html5  --attribute "source-highlighter=pygments" -a "indir=/mnt/e/Github/asciidoc-benchmarks" -a "blockname=table" -s -
```

Replacing the `\include` here with something else works as expected in that the text is surrounded by a source highlighter box.

**Comment by hoadlck** [comment]
Was this problem fixed?  I was trying to recreate it, and am not having any luck.  It is working fine for me.

I was able to convert the example fragment without any errors.  I did change the language from "text" to "txt", as that was what the `source-highlight` program I was using required.  But, no changes other than that.

Here are the versions of my environment.
```bash
pi@maa:~/asciidoc_tests $ python3 --version
Python 3.7.3
pi@maa:~/asciidoc_tests $ uname --all
Linux maa 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux
pi@maa:~/asciidoc_tests $ source-highlight --version
GNU Source-highlight 3.1.8 (library: 4:1:0)
Copyright (C) 1999-2008 Lorenzo Bettini <http://www.lorenzobettini.it>
This program comes with ABSOLUTELY NO WARRANTY.
This is free software; you may redistribute copies of the program
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by MasterOdin** [comment]
I get the same error on master. Are you using the fragment provided in the first post in its own file (`test.txt`) and then how are you invoking asciidoc-py?

**Comment by hoadlck** [comment]
The exact files that I used are contained in [include.zip](https://github.com/asciidoc/asciidoc-py3/files/5656597/include.zip).  As I said earlier, I had to use `txt` instead of `text` because that was the option that the `source-highlight` program I was using required

The command I ran was as follows:
```
% python3 asciidoc.py --backend=html5 include.adoc
```

**Comment by MasterOdin** [comment]
Ah, okay, looks like a communication error on my part. I've updated the original post to hopefully make what the error is a bit more clear and a picture of the actual vs expected output from the two programs.
