### ISSUE TITLE
a2x, utf-8 error with htmlhelp output

### ISSUE THREAD

**Issue by phoyd** [asciidoc/asciidoc-py3#124]
This trivial adoc file ([foo.adoc.txt](https://github.com/asciidoc/asciidoc-py3/files/4825690/foo.adoc.txt)): 
```
$ cat foo.adoc
= Title

text

== Subtitle

subtext


````
...produces this error with the current revision from git: 

```
$  ./asciidoc-py3/a2x.py -v -f htmlhelp foo.adoc
a2x: args: ['-v', '-f', 'htmlhelp', 'foo.adoc']
a2x: resource files: []
a2x: resource directories: ['/home/marco/asciidoc-py3/images', '/home/marco/asciidoc-py3/stylesheets']
a2x: executing: "/home/marco/asciidoc-py3/asciidoc.py" --backend docbook -a "a2x-format=htmlhelp"  --verbose  --out-file "/home/marco/foo.xml" "/home/marco/foo.adoc"




asciidoc: reading: /home/marco/asciidoc-py3/asciidoc.conf
asciidoc: reading: /home/marco/foo.adoc
asciidoc: reading: /home/marco/asciidoc-py3/docbook45.conf
asciidoc: reading: /home/marco/asciidoc-py3/filters/code/code-filter.conf
asciidoc: reading: /home/marco/asciidoc-py3/filters/graphviz/graphviz-filter.conf
asciidoc: reading: /home/marco/asciidoc-py3/filters/latex/latex-filter.conf
asciidoc: reading: /home/marco/asciidoc-py3/filters/music/music-filter.conf
asciidoc: reading: /home/marco/asciidoc-py3/filters/source/source-highlight-filter.conf
asciidoc: reading: /home/marco/asciidoc-py3/lang-en.conf
asciidoc: writing: /home/marco/foo.xml

a2x: executing: "xmllint" --nonet --noout --valid "/home/marco/foo.xml"


a2x: deleting /home/marco/foo.htmlhelp
a2x: creating /home/marco/foo.htmlhelp
a2x: chdir /home/marco
a2x: executing: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0 --stringparam htmlhelp.chm "foo.chm" --stringparam htmlhelp.hhp "foo.hhp" --stringparam htmlhelp.hhk "foo.hhk" --stringparam htmlhelp.hhc "foo.hhc"  --stringparam base.dir "foo.htmlhelp/" "/home/marco/asciidoc-py3/docbook-xsl/htmlhelp.xsl" "/home/marco/foo.xml"

Writing foo.htmlhelp/ar01s01.html for section(_subtitle)
Writing foo.htmlhelp/index.html for article
Writing foo.hhp
Writing foo.hhc

a2x: chdir /home/marco
a2x: finding resources in: /home/marco/foo.htmlhelp/ar01s01.html
Traceback (most recent call last):
  File "./asciidoc-py3/a2x.py", line 1008, in <module>
    a2x.execute()
  File "./asciidoc-py3/a2x.py", line 427, in execute
    self.__getattribute__('to_'+self.format)()
  File "./asciidoc-py3/a2x.py", line 753, in to_htmlhelp
    self.to_chunked()
  File "./asciidoc-py3/a2x.py", line 772, in to_chunked
    self.copy_resources(html_files, src_dir, dst_dir)
  File "./asciidoc-py3/a2x.py", line 636, in copy_resources
    resources += find_resources(
  File "./asciidoc-py3/a2x.py", line 306, in find_resources
    contents = contents.decode(mo.group(1).decode('utf-8') if mo else 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 93: invalid start byte
```

`hexdump -C` shows me indeed, that `foo.htmlhelp/ar01s01.html` contains a `0xa0` character. Also it looks like `foo.htmlhelp/ar01s01.html` declares itscharset as *ISO-8859-1* , which makes the `0xa0` a friendly and legit non breaking space character.  I've tried `-a encoding=utf-8` and `-a encoding=ISO-8859-1` with no avail. The Python 2 version from the other repo also produces an *ISO-8859-1* encoded ar01s01.html with the 0xa0 character, but does not crash at all. 

Not sure if I overlooked something, but my expectation is, that the copy_resources step should recognize the encoding of the files it processes. 

My environment:
```
$ uname -a
Linux MEGATRON 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
# It's Ubuntu 20.04 on WSL1 
$ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
$ git describe --tags
9.0.0-2-g5fbcc21
```

**Comment by MasterOdin** [comment]
Thanks for reporting this. I've opened a PR to fix this issue and so encoding should now be properly detected for html files (it was only properly parsing xml files before). The python2 code was working, but I would consider this largely luck than anything else as it allowed people to be very loosey-goosey with encodings, and is not a great model to hold up.

I do agree that having a2x (and more broadly asciidoc) automatically detecting the encoding would be nice, and to do it in a good number of cases is possible by using an external dependency on [cchardet](https://pypi.org/project/cchardet/), I've not yet put that into place as there's not a great story for installing that dependency, though it's on my radar for 10.0, which moves asciidoc to be installable via pypi. See more discussion on it in #92.
