### ISSUE TITLE
pip3 install asciidoc3 - issues/concerns on AIX-python3-3.7

### ISSUE THREAD

**Issue by aixtools** [asciidoc/asciidoc-py3#79]
Wanted to use asciidoc to create current man pages for git, but cannot get asciidoc3 to run.

```
root@x064:[/home/root]pip3 install asciidoc3
Collecting asciidoc3
  Downloading https://files.pythonhosted.org/packages/be/e9/defb4373cca5e1d42c                                                    d952ee7aeefc1dda0c03d5211c27b6f18e859bea43/asciidoc3-3.1.0.post4.tar.gz (770kB                                                    )
     |################################| 778kB 7.7MB/s
Installing collected packages: asciidoc3
  Running setup.py install for asciidoc3 ... done
Successfully installed asciidoc3-3.1.0.post4
WARNING: You are using pip version 19.2.2, however version 19.2.3 is available                                                    .
You should consider upgrading via the 'pip install --upgrade pip' command.
root@x064:[/home/root]asciidoc
ksh: asciidoc:  not found.
root@x064:[/home/root]asciidoc3
Traceback (most recent call last):
  File "/opt/bin/asciidoc3", line 11, in <module>
    load_entry_point('asciidoc3==3.1.0.post4', 'console_scripts', 'asciidoc3')                                                    ()
  File "/opt/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489,                                                     in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793                                                    , in load_entry_point
    return ep.load()
  File "/opt/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411                                                    , in load
    return self.resolve()
  File "/opt/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417                                                    , in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'asciidoc3'

```

This is what seems to have been "installed"

```
root@x064:[/opt/lib/python3.7]find . | grep asciidoc
./site-packages/asciidoc3-3.1.0.post4-py3.7.egg-info
./site-packages/asciidoc3-3.1.0.post4-py3.7.egg-info/PKG-INFO
./site-packages/asciidoc3-3.1.0.post4-py3.7.egg-info/SOURCES.txt
./site-packages/asciidoc3-3.1.0.post4-py3.7.egg-info/dependency_links.txt
./site-packages/asciidoc3-3.1.0.post4-py3.7.egg-info/entry_points.txt
./site-packages/asciidoc3-3.1.0.post4-py3.7.egg-info/installed-files.txt
./site-packages/asciidoc3-3.1.0.post4-py3.7.egg-info/not-zip-safe
./site-packages/asciidoc3-3.1.0.post4-py3.7.egg-info/top_level.txt
```

Can always be user-error, but generally, it just installs. Maybe the .post4 bit is in the way, but I do not know what to correct. Suggestions welcome.

**Comment by MasterOdin** [comment]
https://pypi.org/project/asciidoc3/ points to https://gitlab.com/asciidoc3/asciidoc3, not here (it's an unfortunate and weird split which you can read through the discussion of in the various issues here and https://github.com/asciidoc3/asciidoc3).

This repo is currently not hosted on the pypi.org yet, though it is making slow progress, tracked in #55).

**Comment by asciidoc3** [comment]
@aixtools
Hi, this is the "unfortunate and weird split" asciidoc3 speaking.
Indeed the PyPI/pip installation as root does not work. That is a known amd intended behavior: because of the many conf-files you need to run 'asciidoc3_postinstall' immediately after 'pip3 install'. This makes only sense as a normal user (not root) with option --user: 'normaluser$ pip3 install --user asciidoc3'. 
For system wide installation (as root) we recommend to download the tarball 'asciidoc3-3.1.0.tar.gz'
All information is found here https://asciidoc3.org

**Comment by aixtools** [comment]
Thanks. I should have replied much earlier.
