### ISSUE TITLE
a2x decoding error when using non-utf8 locales

### ISSUE THREAD

**Issue by marcecj** [asciidoc/asciidoc-py3#92]
Hi, a Gentoo user reported an issue when compiling a UTF-8 encoded document under a C locale (see https://bugs.gentoo.org/705122).  It seems that the issue is that the call to `open()` in `get_source_options()` opens the file in text mode without a specific encoding, in which case `open()` apparently defaults to an encoding that matches the locale.  I saw that https://github.com/asciidoc/asciidoc-py3/pull/5 included a proposed fix for that (by passing an encoding to `open()`), but that was never merged, and it looks like the changes were not part of the successor PRs.  I would think that this would also affect people using other locales that are incompatible with UTF-8.

**Comment by elextr** [comment]
You should be able to specify an encoding on the command line as attribute `encoding` or if the encoding is compatible with ASCII it can be specified as the first line of the file (or at least before the first non-ASCII character).

So for UTF-8 files you should be able to put:
```
:encoding: UTF-8
```
as the first line.

**Comment by marcecj** [comment]
Thanks for the quick reply, but AFAICT that's not the problem.  Perhaps I should have used an example:  The concrete problem in the Gentoo bug report is that the documentation to the nftables project won't build under the "C" locale.  Never mind whether doing that in the first place is a good idea, but in principle I think you could get into trouble in any situation where the document encoding is incompatible with the locale settings.  To test this, I donwloaded the nft.txt file from their repo (https://git.netfilter.org/nftables/tree/doc/nft.txt) and ran the command line used in their build system:

```
bash-4.4$ locale
LANG=de_DE.utf8
LC_CTYPE="de_DE.utf8"
LC_NUMERIC="de_DE.utf8"
LC_TIME="de_DE.utf8"
LC_COLLATE="de_DE.utf8"
LC_MONETARY="de_DE.utf8"
LC_MESSAGES="de_DE.utf8"
LC_PAPER="de_DE.utf8"
LC_NAME="de_DE.utf8"
LC_ADDRESS="de_DE.utf8"
LC_TELEPHONE="de_DE.utf8"
LC_MEASUREMENT="de_DE.utf8"
LC_IDENTIFICATION="de_DE.utf8"
LC_ALL=
bash-4.4$ a2x -L --doctype manpage --format manpage -D . nft.txt
bash-4.4$ LC_ALL="C" a2x -L --doctype manpage --format manpage -D . nft.txt
Traceback (most recent call last):
  File "/usr/bin/a2x", line 931, in <module>
    source_options = get_source_options(sys.argv[-1])
  File "/usr/bin/a2x", line 337, in get_source_options
    for line in f:
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 5987: ordinal not in range(128)
bash-4.4$ LC_ALL="C" a2x -a "encoding=utf-8" -L --doctype manpage --format manpage -D . nft.txt
Traceback (most recent call last):
  File "/usr/bin/a2x", line 931, in <module>
    source_options = get_source_options(sys.argv[-1])
  File "/usr/bin/a2x", line 337, in get_source_options
    for line in f:
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 5987: ordinal not in range(128)
bash-4.4$ a2x -a "encoding=utf-8" -L --doctype manpage --format manpage -D . nft.txt
bash-4.4$ 
```
As you can see, specifying the `encoding` attribute does not help, and how could it, when the code in a2x  (copied from https://github.com/asciidoc/asciidoc-py3/blob/master/a2x.py#L365, but the lines in the version packaged in Gentoo are identical) looks like this:

```
if os.path.isfile(asciidoc_file):
        options = ''
        with open(asciidoc_file) as f:
            for line in f:
                mo = re.search(r'^//\s*a2x:', line)
                if mo:
                    options += ' ' + line[mo.end():].strip()
        parse_options()
```

So the `encoding` specified by the document isn't used anywhere here.  https://github.com/asciidoc/asciidoc-py3/pull/5 suggested passing `encoding="utf-8"` to `open()`, see https://github.com/asciidoc/asciidoc-py3/pull/5/files#diff-d293f8246a581df14d2c7369b5bab885R305-R342, but that was left out or forgotten in the successor PRs (maybe a reason was given, but I didn't dig through all of them to find out; perhaps because using the document encoding would be better).  In the Gentoo bug report, it was suggested to open the file in binary mode and to use `.decode()`, like so:

```
        with open(asciidoc_file, 'rb') as f:
            for line in f:
                mo = re.search(b'^//\s*a2x:', line)
                if mo:
                    options += ' ' + line[mo.end():].strip().decode('ascii')
```

However, you should probably still use the document encoding in that case, so I suppose that isn't any better (unless option strings really can only be ASCII).

Also, just to be sure, I tested with the master branch, which yielded the same results.

**Comment by hoadlck** [comment]
Character encoding is something that I have wanted to test more closely with the AsciiDoc 3.x port.  When reading text with Python 3, I always run into problems where users end up creating text files in strange encodings (or invalid encodings).  I either try reading the text in various encodings, or just returning an error so the user will fix things.  Neither of which options are very desirable.

I have worked with other Python modules where a Python 2.7 implementation has no problems, but a Python 3.x errors out because of these situations.  I assume because Python 3.x is more rigorous about encoding.

If the document is declaring the encoding explicitly, then I can see the point of throwing an error.  But, if it is not, then it seems better to be more accepting of arbitrary user input.

I have heard of [chardet](https://chardet.readthedocs.io/en/latest/usage.html) which attempts to detect encoding using Mozilla's algorithm.  I am not sure if this is the answer, but I think there needs to be something more user friendly like this.

**Comment by hoadlck** [comment]
As a simpler example, I created a file [bad_encoding_cp1250.txt](https://github.com/asciidoc/asciidoc-py3/files/4082952/bad_encoding_cp1250.txt).  The file is actually in WIndows-1250 encoding, even though I would have a general expectation that a text file would be in UTF-8.  When I try to convert this file, I get the following error:

```bash
(544)% python asciidoc.py  bad_encoding_cp1250.txt
asciidoc: FAILED: unexpected error:
asciidoc: ------------------------------------------------------------
Traceback (most recent call last):
  File "asciidoc.py", line 6120, in asciidoc
    reader.open(infile)
  File "asciidoc.py", line 4252, in open
    if self.read():
  File "asciidoc.py", line 4411, in read
    result = self.read_super()
  File "asciidoc.py", line 4405, in read_super
    result = Reader1.read(self, self.skip)
  File "asciidoc.py", line 4274, in read
    s = self.f.readline()
  File "C:\python36\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 389: invalid start byte
```

If I change [this](https://github.com/asciidoc/asciidoc-py3/blob/9.0.0rc1/asciidoc.py#L4244) line in asciidoc.py from
 ```    self.f = open(fname, 'r', encoding='utf-8')```
to
 ```    self.f = open(fname, 'r', encoding='windows-1250')```
everything works fine.  Likewise, if I change the line to 
 ```    self.f = open(fname, 'r')```
everything also works (I assume because my specific local uses 'windows-1250' as a default encoding).

The kludge that I have done in other programs is to try opening the file with successive encodings.  It if fails under utf-8, then try Windows-1250.  But, some users end up using [Shift JIS](https://en.wikipedia.org/wiki/Shift_JIS), so then what do you do?  Iterating over every possible encoding does not seem sensible.  But, if we could detect the encoding, that would be easier for users.

**Comment by elextr** [comment]
@marcecj looks like that code hasn't changed since Python 2 Asciidoc.  Possibly it worked then because Python 2 ignored encoding errors.

So until someone teaches a2x to understand encodings it will have to be worked around by running a2x in the locale of the file.

**Comment by elextr** [comment]
@hoadlck this issue is about `a2x` not `asciidoc`, please make a separate issue.

**Comment by MasterOdin** [comment]
Something to note here is that [asciidoctor](https://asciidoctor.org/docs/user-manual/#include-nonasciidoc) seems to want everything in UTF-8, and will convert down to it as necessary. However, I am not sure how it handles stuff like windows-1250 to UTF-8.

> I have worked with other Python modules where a Python 2.7 implementation has no problems, but a Python 3.x errors out because of these situations. I assume because Python 3.x is more rigorous about encoding.

This is due to the fact that Python2, the strings were technically just byte strings with just weird syntactic sugar on top of it to make it look like strings, which made possible these sorts of loose encoding operations. I am all in-favor of being rigorous about knowing what encoding you are in, and would not support a move back to python2-esque behavior (as there's way too many ways to blow your feet off with it).

> I have heard of chardet which attempts to detect encoding using Mozilla's algorithm. I am not sure if this is the answer, but I think there needs to be something more user friendly like this.

> The kludge that I have done in other programs is to try opening the file with successive encodings. It if fails under utf-8, then try Windows-1250. But, some users end up using Shift JIS, so then what do you do? Iterating over every possible encoding does not seem sensible. But, if we could detect the encoding, that would be easier for users.

chardet works really well to achieve your second point and is in-fact how things like [requests](https://pypi.org/project/requests) work on getting the encoding of a response from a website that does not explicitly request it. I (in a much older build) toyed with the concept of using chardet to get the encoding for a document before I settled with defaulting to just use utf-8, but it did not make any final PRs. I do think this is the appropriate way in the future though to complete a similar operation as asciidoctor (load any encoding, but cast it to utf-8 before doing anything).

**Comment by asciidoc3** [comment]
Hi,
@marcecj @elextr @hoadlck @MasterOdin
this issue may be solved using asciidoc3 (see https://asciidoc3.org or https://gitlab.com/asciidoc3/asciidoc3). One of the features of asciidoc3 is the possibility of **choosing the input-encoding** (btw, the output-encoding, input/output-errors, too). So you can type

`asciidoc3 -a input-encoding=cp1250 bad_encoding_cp1250.txt`

and you'll get a **html-output** with the correct characters.

To produce a 'good looking' **pdf** just execute 
`asciidoc3 -a input-encoding=cp1250 -b docbook bad_encoding_cp1250.txt && a2x3 -f pdf bad_encoding_cp1250.xml
`
and everything goes the right way.

**Comment by hoadlck** [comment]
This issue is about updating the original AsciiDoc to support the various encodings...not using some other tool to convert a specific document.  This is specifically a backwards compatibility issue: if there is a file that the 2.x version of AsciiDoc converted (because of the older versions of Python and their less strict enforcement of character encoding), then the newer version should convert in a similar way.

In the specific file that I uploaded, I believe that the asciidoc-py3 implementation would process it properly if I passed the encoding on the command line.  The immediate problem is in how a2x handles the scanning for options in the original AsciiDoc input file.

If you look [here](https://gitlab.com/asciidoc3/asciidoc3/blob/master/a2x3.py#L412), you see that the asciidoc3 fork has the same flaw that we are talking about in this issue.  When we get this fixed in the original asciidoc-py3 project, you may want to pick up the change.

**Comment by hoadlck** [comment]
I have been doing some research, and wanted to put what my proposal for "proper" processing of the `a2x` options would be.  While the scope of this issue is just the `a2x` options search, I am proposing that a future pull request would use this same logic for regular `asciidoc` processing.

In the discussion of #93 (which has been abandoned), @elextr made a
[comment](https://github.com/asciidoc/asciidoc-py3/pull/93#issuecomment-576519870) about his thoughts on the logic:
> What is "correct" for encoding handling is somewhat subjective and depends on
> use-case and personal preference. What I can suggest is what works for me on
> another project.
>  * Open the file as bytes and check if a regular expression (which has the
>    BOMs and that projects equivalent of :encoding: in it) matches at the
>    start of the file.
>  * If no match use the command line option if specified, else utf-8.
>    It is a personal decision to have an encoding in the file contents override
>    the command line (with warning) but it means that a file with an incorrect
>    BOM or encoding specification can't be processed until its fixed.
>  * If the regex did match and it is one of the BOMs, use that to set the
>    encoding, or if its the equivalent of :encoding: read the value for that
>    and use it instead.
>  * The file is then read from the end of the BOM/:encoding: value using the
>    appropriate encoding.
>
> Encoding can be UTF-8, UTF-16 (le or be), or UTF-32 (le or be).
> These can also be preceded by a BOM.

In reviewing the AsciiDoc documentation, I found a statement [here](https://www.methods.co.nz/asciidoc/chunked/ch08.html#X95) about encoding. It says that header attributes are overridden by command-line attributes. That is different from what @elextr had outlined, but it does follow the same pattern as other tools (e.g. makefiles).  The documentation also says "If the header contains non-UTF-8 characters then the encoding must precede the header (either in the document or on the command-line)."

So, with the above in mind, here is the proposed logic:
 * Open File In Bytes
   This gives an array of bytes that will be probed by the rest of the logic.
 * Check Beginning Of Byte Array For BOM
   If BOM found, then remove it from the byte stream, but remember what it
   has told us.
   - Look For codecs.BOM_UTF8     (b'\xef\xbb\xbf')
   - Look For codecs.BOM_UTF32_BE (b'\x00\x00\xfe\xff')
   - Look For codecs.BOM_UTF32_LE (b'\xff\xfe\x00\x00')
   - Look For codecs.BOM_UTF16_BE (b'\xfe\xff')
   - Look For codecs.BOM_UTF16_LE (b'\xff\xfe')
   The first match from one of the above means that we will attempt to
   decode the rest of the byte array with the corresponding encoding.  While
   it is ugly, the BOM is a robust way to indicate the encoding.
   If there is no match, then continue on.
   If there is an error doing the decoding, then issue warning and continue
   to next step.
 * Check For `encoding` Attribute From Command Line
   If it exists, then attempt to decode the byte array using that option.
   If there is an error doing the decoding, then issue warning and continue
   to next step.
 * Check For `:encoding:` Attribute In Input File Header
   Finding the `:encoding:` attribute in the file is simple for an encoding
   like UTF-8, but UTF-16 or UTF-32 (both with possible big/little endian
   variants) is more problematical.  I am unsure if a naive check for a new
   line character (needed to find the end of the header) might falsely find
   a match for some odd character encoded in UTF-16.
   If there is no match, then continue on to next step.
   If there is a `:encoding:` attribute found, attempt to decode the byte
   array.  Issue a warning if that fails (either because the encoding type
   was not recognized, or because the decoding just failed).  Failure will
   cause the logic to go to the next step.
 * Attempt To Decode Byte Array Using UTF-8
   This is the normal expectation for AsciiDoc and the rest of the planet.
   If there is an error doing the decoding, then issue warning and continue
   to next step.
 * Use [chardet](https://chardet.readthedocs.io/en/latest/) To Detect Encoding
   Take results from detect process and attempt to decode byte array.
   If there is an error doing the decoding, then issue final error and we are
   done.

Any success in the attempts to decode the byte array in the above logic results in the program proceeded with that encoding.  Note that the encoding detected may end up replacing the attribute option passed on the command line.

I also am uncertain about including an external dependency like `chardet` at this time.  The AsciiDoc module has always been self contained, so an external dependency would be a major shift.  I am wondering if the 9.x AsciiDoc releases should be stay away from external dependencies (so users that just want to get away from the 2.7 Python dependency will have an easy migration).  Then `chardet` could be added for the 10.x releases with more major changes to AsciiDoc.

Thoughts?

P.S. I was wondering "What Would AsciiDoctor Do?", so I downloaded it and tried some example files.  It does have trouble with UTF-32, but was taking some other encodings.  I had trouble getting it to accept some encodings by passing the encoding attribute on the command line, but that may be because it was not accepting the encoding strings I was passing in.  It definitely works better in UTF-8.

**Comment by elextr** [comment]
> It says that header attributes are overridden by command-line attributes.

Yes, "encoding" isn't special, its a standard attribute, and thats the default behaviour for attributes defined on the command line [without @](http://asciidoc.org/manpage.html).  To be clear my use-case has a specific encoding cl option, so there was no default behaviour and either choice was available.

Its probably not relevant to your a2x use-case, but on the basis that the same code should be used to select encoding in both a2x and Asciidoc, what should Asciidoc do for included files?  In particular what if the included file has a different `:encoding:` in it? (Note: I have not checked what it actually does now).

Also not part of this issue, but related, is that at some point input encoding and output encoding need to be separated.  ATM they are both set by the encoding attribute, which was good for Python 2 where the text in memory wasn't actually converted, but with Python 3 it has to be converted on input and converted back on output so there is no benefit of making them the same and would allow standard UTF-8 for generated HTML irrespective of the input encoding.

> Finding the :encoding: attribute in the file is simple for an encoding like UTF-8, but UTF-16 or UTF-32 (both with possible big/little endian variants) is more problematical. 

Yes, UTF-16 and UTF-32 should use the BOM, the `:encoding:` mechanism only works for byte oriented encodings with ASCII as a subset.  Other encodings are a use-case where the cl setting is required.

> Then chardet could be added for the 10.x releases with more major changes to AsciiDoc.

Yeah, things that are incompatible should be major releases anyway according to semver principles, and potentially handling a file as a different encoding definitely comes under the "incompatible" banner.

> "What Would AsciiDoctor Do?"

IIUC Asciidoctor initially tried to be as compatible with Asciidoc Python 2 as Ruby reasonably allowed, but these days its firmly in the "UTF-8 preferred" camp.

Finally a general comment on the "try something and use the first one that converts without error" paradigm.  As you know many files will successfully convert with multiple encoding (well decoding actually) methods, but just because it had no errors does not mean it got the same set of code points as the file in the original encoding.  Thats why the project I posted about made the decision that the encoding must be decided by a deterministic (and fairly simple) process and only that one encoding is actually applied.  If it fails to convert, the process stops so the user can fix the problem, if it converts without error its likely to be right, since it was explicitly specified (or defaulted to UTF-8).

**Comment by MasterOdin** [comment]
Re-reading this, and having a good amount of time to think on this, my view is the order should be for determining what encoding to use:
1. user gives encoding on command-line.
2. :encoding: specified in file (assume ascii string)
3. check BOM
4. assume UTF-8

For steps 1 & 2, if either fail to decode the file, I believe the process should fail noisily and not just try and keep going. It can be assumed there is a reason the user wants those (bad) encodings, and it should be up to the user then to fix things on their end. We can potentially get descriptive with our error message if a BOM exists, but we should not (I think) override user choice with BOM, regardless of how good a signal it is for encoding.

> Then chardet could be added for the 10.x releases with more major changes to AsciiDoc.

Yeah, in 10.x release, I plan to move also a pip based installation policy so folding in chardet for that would be a lot easier/possible than currently.

**Comment by elextr** [comment]
On Sat, 15 Feb 2020 at 03:32, Matthew Peveler <notifications@github.com>
wrote:

> Re-reading this, and having a good amount of time to think on this, my
> view is the order should be for determining what encoding to use:
>
>    1. user gives encoding on command-line.
>    2. :encoding: specified in file (assume ascii string)
>    3. check BOM
>    4. assume UTF-8
>
>
Yes, I agree thats sensible, but have the encoding on the CL obey the
normal overriding rules, ie if the user adds an @ then the file overrides
the CL.  In that case the CL is specifying a default encoding for unmarked
files.

If that is not obeyed then there is no way of having included files with a
different encoding to the main file, even if they are marked, since only
one encoding can be specified on the command line and it overrides the file
mark.

>
>
> For steps 1 & 2, if either fail to decode the file, I believe the process
> should fail noisily and not just try and keep going. It can be assumed
> there is a reason the user wants those (bad) encodings, and it should be up
> to the user then to fix things on their end.
>

Agreed


> We can potentially get descriptive with our error message if a BOM exists,
> but we should not (I think) override user choice with BOM, regardless of
> how good a signal it is for encoding.
>
> Then chardet could be added for the 10.x releases with more major changes
> to AsciiDoc.
>
> Yeah, in 10.x release, I plan to move also a pip based installation policy
> so folding in chardet for that would be a lot easier/possible than
> currently.
>

The issue with chardet is it isn't stable, as the pypi page said at the
date I wrote this "Our ISO-8859-2 and windows-1250 (Hungarian) probers have
been temporarily disabled until we can retrain the models.".  So users with
different versions of chardet may get different results, or the results
might change when the version of Asciidoc/chardet is upgraded.

To perhaps explain further why its important that the process is
deterministic and doesn't depend on versions or locales.  Take the example
of Asciidoc being used to document a piece of software.  A user of that
software (who has no idea of Asciidoc, and who should not need to) decides
to upgrade to the latest development version, maybe it has an important
bugfix, so the user downloads a git clone or tarball, grumbles about having
to `pip install asciidoc`, types the usual `configure; make install` but
because either they have a different version of Asciidoc or locale or
something else different to the developers of the software, a different
encoding is used, and they get a mixed up manual.  Now everyone is stuck,
that projects developer doesn't have the environment the user has, so they
can't identify and fix the problem, the user doesn't understand whats wrong
and has a useless manual and blames the developer, who blames Asciidoc.  It
really is important that the process is deterministic, and not dependent on
environment.

Cheers
Lex

**Comment by ghost** [comment]
Ping: is this closed or not? I see it was proposed for v10 but still here
