### ISSUE TITLE
UnboundLocalError: local variable 'asciidoc3' referenced before assignment

### ISSUE THREAD

**Issue by svyotov** [asciidoc/asciidoc-py3#97]
```
>>> from asciidoc3 import asciidoc3api
>>> asciidoc3 = asciidoc3api.AsciiDoc3API()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/insert_username/.virtualenvs/asciidoc3api-venv/lib/python3.7/site-packages/asciidoc3/asciidoc3api.py", line 156, in __init__
    self.__import_asciidoc3()
  File "/home/insert_username/.virtualenvs/asciidoc3api-venv/lib/python3.7/site-packages/asciidoc3/asciidoc3api.py", line 185, in __import_asciidoc3
    self.asciidoc3 = asciidoc3
UnboundLocalError: local variable 'asciidoc3' referenced before assignment
```

asciidoc3==3.1.0.post5

**Comment by MasterOdin** [comment]
Looks like you're using asciidoc3, which is an unrelated fork of asciidoc-py3. You should file an issue there to get help: https://gitlab.com/asciidoc3/asciidoc3.
